### ISSUE TITLE
Black strips on resized image

### ISSUE THREAD

**Issue by alexweb-zz** [kohana/image#23]
When I'm resizing image some strange black borders appear on thumbnail. 
My code is next (it's Yii2 extension that uses your library):

``` php
            /*
             * Save thumbnail image
             */
            $thumbPath=$dir . '/' . self::getThumbPrefix() . $image->name;
            $saved=Yii::$app->image->load($path)
                ->resize(self::THUMB_WIDTH, self::THUMB_HEIGHT, yii\image\drivers\Image::INVERSE)
                ->crop(self::THUMB_WIDTH, self::THUMB_HEIGHT)
                ->save($thumbPath, $quality = 100);
            if($saved==false)
                throw new HttpException(500, 'Unable to save image thumbnail.');
```

Original image:

![reczycz_belapan150714-4r4ub](https://cloud.githubusercontent.com/assets/960052/8683746/28bfc4ce-2a7d-11e5-854b-f405448ff305.jpg)

Final image:

![224x224_1_1436904097](https://cloud.githubusercontent.com/assets/960052/8683764/423b9e32-2a7d-11e5-9955-d4d56aba391d.jpg)

Please check top and bottom borders. Do you know why does it happen?

**Comment by acoulton** [comment]
Most likely you're resizing in a mode that fits the image into the aspect ratio of the thumbnail rather than cropping it.

Are you definitely in the right place though? Your code looks like you're using Yii, not kohana.

**Comment by alexweb-zz** [comment]
This code first resizes image by the shortest side. Then it cuts image to make it square. 
As I told above its Yii2 extension(wraper) that uses your library https://github.com/yurkinx/yii2-image

**Comment by acoulton** [comment]
Which driver are you using?

Can you save and post the image created after `resize` - before `crop`?

Sorry I didn't see you'd said about the Yii2 extension - I guess you edited the description after creating, as it wasn't in the email notification.

**Comment by alexweb-zz** [comment]
I'm using Kohana_Image::INVERSE

Here is the image after resize(), but without crop():
![224x224_2_1437406033](https://cloud.githubusercontent.com/assets/960052/8779637/f8f8ed76-2f0c-11e5-87c8-5a14b5defab5.jpg)

**Comment by alexweb-zz** [comment]
Ok, I found the reason. The problem is not in your library.
Before saving image I fix image orientation using this method (it rotates image according to EXIF data):

``` php
    public static function fixImageOrientation(UploadedFile $file)
    {
        if(!empty($file->tempName)
            && exif_imagetype($file->tempName) == IMAGETYPE_JPEG){
            $image = imagecreatefromjpeg($file->tempName);
            $image = imagerotate($image, array_values([0, 0, 0, 180, 0, 0, -90, 0, 90])[@exif_read_data($file->tempName)['Orientation'] ?: 0], 0);
            imagejpeg($image, $file->tempName);
        }
    }
```

And that method adds these strips...

**Comment by acoulton** [comment]
@alexweb thanks for letting us know, glad you got sorted.
